### ISSUE TITLE
ansible-galaxy install does not work - https://github.com/jivesoftware/ansible-consul/archive/1.3.tar.gz doesnt exist

### ISSUE THREAD

**Issue by millerjp** [savagegus/ansible-consul#119]
ansible-galaxy install savagegus.consul
- downloading role 'consul', owned by savagegus
- downloading role from https://github.com/jivesoftware/ansible-consul/archive/1.3.tar.gz
- error: failed to download the file.
- savagegus.consul was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.

The role tarball doesnt exist.

**Comment by savagegus** [comment]
Looks like that should actually be:
`ansible-galaxy install savagegus.ansible-consul`
