### ISSUE TITLE
disable_update_check parameter should be configurable

### ISSUE THREAD

**Issue by berendt** [savagegus/ansible-consul#134]
I do not want to check for updates, the disable_update_check parameter (https://www.consul.io/docs/agent/options.html#disable_update_check) should be configurable.

**Comment by sidick** [comment]
Please see #130 :)

**Comment by berendt** [comment]
Just found it ;) Merge of this feature possible? Not sure why the PR is still pending.

**Comment by savagegus** [comment]
Merged!
