### ISSUE TITLE
provisioning failed 

### ISSUE THREAD

**Issue by rikibarel** [savagegus/ansible-consul#146]
Hi,
Provisioning failed with error:
TASK [savagegus.consul : add CONSUL_RPC_ADDR to .bashrc] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: become_user"}

to resolved the failure:
I removed the following lines:
    become=yes
    become_user={{ consul_user }}
from tasks/install.yml -->name: add CONSUL_RPC_ADDR to .bashrc

and rerun
.bashrc file created 
ansible finished successfully 

please advise
Riki

**Comment by sidick** [comment]
Which version of Ansible is this on?

**Comment by rikibarel** [comment]
ansible 2.1.0.0
