### ISSUE TITLE
How to make consul command available to sudo?

### ISSUE THREAD

**Issue by MrMMorris** [savagegus/ansible-consul#25]
I see that there is a task that appends the executable onto $PATH, but if I run `sudu su` and then try and run `consul` I get `consul: command not found`.

Might be a simple question, but is there a way to make the executable available to sudo without changing the consul user?

Thanks!

**Comment by savagegus** [comment]
sudo su - consul ?

**Comment by MrMMorris** [comment]
sorry, I guess I didn't explain very well. I mean, how can I run `consul` cli as root?
