### ISSUE TITLE
UndefinedError: 'ansible_fqdn' is undefined

### ISSUE THREAD

**Issue by sheldonh** [savagegus/ansible-consul#39]
This role is working wonderfully under ansible-1.9.1, thanks.

Just a heads up, though. It breaks with ansible-2.0.0 devel:

```
TASK [savagegus.consul : savagegus.consul : consul config file] *****************
fatal: [i-a001010a]: FAILED! => {"msg": "UndefinedError: 'ansible_fqdn' is undefined", "failed": true, "changed": false}
fatal: [i-a101010b]: FAILED! => {"msg": "UndefinedError: 'ansible_fqdn' is undefined", "failed": true, "changed": false}
fatal: [i-be010114]: FAILED! => {"msg": "UndefinedError: 'ansible_fqdn' is undefined", "failed": true, "changed": false}
```

The hosts in question were created by the ec2 module, and their hostgroup was created with the add_host module.

**Comment by bhavicp** [comment]
I seem to be hitting this bug in the latest dlevel (14th Sep) I can't get fqdn or ipv4's

    fatal: [apollo.obtrix.net]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: ERROR! 'ansible_fqdn' is undefined"}
    fatal: [apollo.obtrix.net]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: ERROR! 'ansible_default_ipv4' is undefined"

**Comment by savagegus** [comment]
I'm using on ansible 2.0 with ec2 without issue, anyone else able to reproduce?

**Comment by sheldonh** [comment]
Nah, we're using Ansible 2.0 on EC2 too. Must have been one of many -devel regressions that got sorted out before release. :-)

**Comment by savagegus** [comment]
Rad, thanks for the followup.

**Comment by NerrickT** [comment]
I have the same issue with 2.0.0.2. Did anyone find a fix?
