### ISSUE TITLE
option for ui without nginx

### ISSUE THREAD

**Issue by sixspot** [savagegus/ansible-consul#69]
With the "-ui-dir /path/to/ui" option the consul ui is available at http://localhost:8500/ui by default; however, ansible-consul has a curious dependency on an Ubuntu specific nginx role to enable the ui. It seems out of place. Can we have a simple ui option?

**Comment by victorcoder** [comment]
+1

**Comment by RockingRolli** [comment]
+1

**Comment by trumant** [comment]
#70 removes the nginx role dependency altogether but as noted, before making any changes to the install-ui functionality we should really get a TestKitchen test suite together for it.

**Comment by palmerabollo** [comment]
+1

**Comment by palmerabollo** [comment]
+1

#70 needs to change meta/main.yml to add a condition to the dependencies (when `consul_enable_nginx_config == true`)

```yml
dependencies:
  - { role: franklinkim.nginx, when: consul_is_ui == true and consul_enable_nginx_config and ansible_os_family == "Debian"}
  - { role: geerlingguy.nginx, when: consul_is_ui == true and consul_enable_nginx_config and ansible_os_family == "RedHat"}
```

**Comment by trumant** [comment]
FYI, there is now a TestKitchen test suite around the UI

**Comment by savagegus** [comment]
:+1:

**Comment by spinx** [comment]
Did a PR for this: #90
