### ISSUE TITLE
probably redundant service start

### ISSUE THREAD

**Issue by sixspot** [savagegus/ansible-consul#76]
The last line of tasks/main.yml runs tasks/service.yml, starts consul if not started:

    - service: >
      name=consul
      state=running
 
The next step is handlers/main.yml, which restarts consul:

    - name: restart consul
      action: service name=consul state=restarted enabled=yes

(Note the older "action: service" line. The newer "server: name=foo" is used a few tasks later.)

[edit, again: There's something I don't understand about leadership election. I get no election on restart.] 

They're almost the same, but not quite. My three server "datacenter"  (Debian, systemd, with bootstrap_expect: 3) loses leadership on the restart and can't seem to regain it. A debug task shows Leadership is gained; that runs before the handler

I removed the service.yml include and things seem to work as expected. I haven't figured out why the line is there. Maybe there's some difference with Ansible 2?

**Comment by sheldonh** [comment]
I just got bitten by this. Lost a consul cluster because consul was restarted for no reason.

It wasn't a production cluster. I was testing idempotence of the latest savagegus.consul before going live. The last version we used was f1be2ba1, which did not restart consul on Ansible runs following initial setup.

**Comment by sheldonh** [comment]
Fixed in e9098e8. Please consider releasing to Ansible Galaxy soon.

**Comment by savagegus** [comment]
Will do. 





On Thu, Feb 25, 2016 at 1:58 AM -0800, "Sheldon Hearn" <notifications@github.com> wrote:












Fixed in e9098e8. Please consider releasing to Ansible Galaxy soon.
