### ISSUE TITLE
Minor: consul_advertise_address not documented

### ISSUE THREAD

**Issue by palmerabollo** [savagegus/ansible-consul#79]
The role variable exists and is used in the consul.conf.j2 template, but is not documented in the README. The property doesn't have a default value, so I'm not sure about where is the best place to add it.

**Comment by DavidWittman** [comment]
@palmerabollo If you do not define `consul_advertise_address` it is not added to the configuration. From the [Consul documentation](https://www.consul.io/docs/agent/options.html):

> `-advertise` - The advertise address is used to change the address that we advertise to other nodes in the cluster. By default, the -bind address is advertised.

That said, I do agree that this should be added to the README.
