### ISSUE TITLE
Docker containers cannot hit dnsmasq due to loopback restriction

### ISSUE THREAD

**Issue by MrMMorris** [savagegus/ansible-consul#95]
So I recently upgraded to 0.6.0 and along with that I used a newer version of this role. There was a lot to grok, but everything seemed to work for my Consul server so I moved onto upgrading one of my clients. Things seemed to work on the Consul side after the upgrade until I realized that my docker containers could not resolve hosts using Consul DNS. After some troubleshooting, I could only get them to be able to use the DNS if `-p 8600` was specified along with `dig`. That's weird... so I started to take a look at what had changed from the older role version I was using. After a LOT of testing, I finally found the culprit:

https://github.com/savagegus/ansible-consul/blob/master/tasks/dnsmasq.yml#L31-L44

**Why was this added?** @trumant

Doesn't this mean that anything outside of the local host (such as Docker containers) cannot go through dnsmasq for DNS lookups?

**Comment by MrMMorris** [comment]
I see that it was added to reduce the Dnsmasq threat surface. How do you suggest it stay open to Docker containers? maybe adding the docker0 interface (172.17.42.1) as well?

**Comment by trumant** [comment]
@MrMMorris - the restriction was implemented based on various security recommendations. I'm not using Consul with Docker, so I didn't realize the effect the config would have in that regard.

**Comment by MrMMorris** [comment]
thanks for the quick response! yea, it's a pretty huge effect and I'm sure a lot of people are using Docker with Consul. I can try my suggested fix to see if that works.

**Comment by trumant** [comment]
I think your suggested approach makes sense.

**Comment by savagegus** [comment]
I'm back to work today so I'll look at merging asap.

**Comment by MrMMorris** [comment]
alright, let me test things

**Comment by MrMMorris** [comment]
done: https://github.com/savagegus/ansible-consul/pull/96

I don't have any tests as I'm not sure if your kitchen setup includes a Docker install.
